### ISSUE TITLE
UDP connection trigger crash - panic: Incrementing non-positive count 0xc000222380 on stack.PacketBuffer

### ISSUE THREAD

**Issue by darkr4y** [nicocha30/ligolo-ng#20]
crash info:
```
panic: Incrementing non-positive count 0xc000222380 on stack.PacketBuffer

goroutine 90 [running]:
github.com/nicocha30/gvisor-ligolo/pkg/tcpip/stack.(*packetBufferRefs).IncRef(0xc000222380)
        /home/runner/go/pkg/mod/github.com/nicocha30/gvisor-ligolo@v0.0.0-20220711100921-110ade85d411/pkg/tcpip/stack/packet_buffer_refs.go:80 +0x105
github.com/nicocha30/gvisor-ligolo/pkg/tcpip/stack.(*PacketBuffer).IncRef(...)
        /home/runner/go/pkg/mod/github.com/nicocha30/gvisor-ligolo@v0.0.0-20220711100921-110ade85d411/pkg/tcpip/stack/packet_buffer.go:190
github.com/nicocha30/gvisor-ligolo/pkg/tcpip/transport/udp.(*endpoint).HandlePacket(0xc000222a80, {0x35, {0xc00025c3a0, 0x4}, 0xd332, {0xc00025c39c, 0x4}}, 0xc000222380)
        /home/runner/go/pkg/mod/github.com/nicocha30/gvisor-ligolo@v0.0.0-20220711100921-110ade85d411/pkg/tcpip/transport/udp/endpoint.go:964 +0x2ef
github.com/nicocha30/gvisor-ligolo/pkg/tcpip/transport/udp.(*ForwarderRequest).CreateEndpoint(0xc000232b00, 0x2)
        /home/runner/go/pkg/mod/github.com/nicocha30/gvisor-ligolo@v0.0.0-20220711100921-110ade85d411/pkg/tcpip/transport/udp/forwarder.go:100 +0x3c6
github.com/nicocha30/ligolo-ng/pkg/proxy/netstack.HandlePacket.func1()
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/handlers.go:141 +0x47f
created by github.com/nicocha30/ligolo-ng/pkg/proxy/netstack.HandlePacket
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/handlers.go:128 +0x8f7
```

how to produce:
when agent connected and start tunneling,
on client side:
`$ ncat -lvup 53`
on server side:
`$ ncat -vu client-ip 53` and then send any buffer like `aaaa`, the server side will crash.
maybe it is a bug relate to gvisor, ref issue https://github.com/tailscale/tailscale/issues/4144

**Comment by nicocha30** [comment]
Hey @darkr4y 

Thanks for reporting this issue.
Ligolo-ng v0.4.1 should address this problem.

https://github.com/nicocha30/ligolo-ng/releases/tag/v0.4.1
